// Code generated by MockGen. DO NOT EDIT.
// Source: controller/customer_controller.go
//
// Generated by this command:
//
//	mockgen -source=controller/customer_controller.go -destination=controller/mocks/customer_controller_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	fiber "github.com/gofiber/fiber/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerController is a mock of CustomerController interface.
type MockCustomerController struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerControllerMockRecorder
	isgomock struct{}
}

// MockCustomerControllerMockRecorder is the mock recorder for MockCustomerController.
type MockCustomerControllerMockRecorder struct {
	mock *MockCustomerController
}

// NewMockCustomerController creates a new mock instance.
func NewMockCustomerController(ctrl *gomock.Controller) *MockCustomerController {
	mock := &MockCustomerController{ctrl: ctrl}
	mock.recorder = &MockCustomerControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerController) EXPECT() *MockCustomerControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerController) Create(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCustomerControllerMockRecorder) Create(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerController)(nil).Create), c)
}

// Delete mocks base method.
func (m *MockCustomerController) Delete(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerControllerMockRecorder) Delete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerController)(nil).Delete), c)
}

// FindAll mocks base method.
func (m *MockCustomerController) FindAll(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCustomerControllerMockRecorder) FindAll(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCustomerController)(nil).FindAll), c)
}

// FindById mocks base method.
func (m *MockCustomerController) FindById(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindById indicates an expected call of FindById.
func (mr *MockCustomerControllerMockRecorder) FindById(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockCustomerController)(nil).FindById), c)
}

// Update mocks base method.
func (m *MockCustomerController) Update(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomerControllerMockRecorder) Update(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerController)(nil).Update), c)
}
